---
- name: install apt utils
  apt:
          name: apt-utils
          state: latest
          update_cache: yes

- name: install composer for php
  apt:
          name: composer
          state: latest

- name: clean apt
  shell: "apt-get clean"

- name: add ppa
  shell: "apt-get update && apt-get install -y language-pack-en-base && export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8 && apt-get install -y software-properties-common && add-apt-repository -y ppa:ondrej/php && add-apt-repository -y ppa:ondrej/nginx-mainline"

- name: install php 7.2
  apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
  with_items:
          - php7.2-cli
          - php7.2-fpm
          - php7.2-curl
          - php7.2-intl
          - php7.2-json
          - php7.2-mysql

- name: copy php fpm conf
  copy:
          src: php-fpm.conf
          dest: /etc/php/7.2/fpm

- name: copy php fpm ini
  copy:
          src: php.ini
          dest: /etc/php/7.2/fpm

- name: copy php www.conf
  copy:
          src: www.conf
          dest: /etc/php/7.2/fpm/pool.d
- name: copy info.php
  copy:
          src: info.php
          dest: /var/www/html
          owner: root
          group: root
          mode: 0644

